export const CONFIRM_EMAIL = 'CONFIRM_EMAIL'
export const CONFIRM_EMAIL_SUCCESSFUL = 'CONFIRM_EMAIL_SUCCESSFUL'
export const CONFIRM_EMAIL_FAILED = 'CONFIRM_EMAIL_FAILED'
export const RESET_CONFIRMEMAIL_FLAG = 'RESET_CONFIRMEMAIL_FLAG'
